#!/bin/bash

# See https://hub.docker.com/_/postgres
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -v SERVER_PASSWORD="'$SERVER_PASSWORD'" -v ADMIN_PASSWORD="'$ADMIN_PASSWORD'" -v SYNC_PASSWORD="'$SYNC_PASSWORD'" -v NOTIFICATION_DISPATCHER_PASSWORD="'$NOTIFICATION_DISPATCHER_PASSWORD'" <<-EOSQL
    CREATE ROLE server WITH LOGIN PASSWORD :SERVER_PASSWORD;
    CREATE ROLE admin WITH LOGIN PASSWORD :ADMIN_PASSWORD CREATEROLE SUPERUSER;
    CREATE ROLE sync WITH LOGIN PASSWORD :SYNC_PASSWORD CREATEROLE BYPASSRLS;
    CREATE ROLE notification_dispatcher WITH LOGIN PASSWORD :NOTIFICATION_DISPATCHER_PASSWORD;
    CREATE SCHEMA flyway;
    ALTER SCHEMA flyway OWNER TO admin;
    ALTER SCHEMA public OWNER TO admin;
EOSQL
